version: "3.4"

# Put environment, ports and other PRODUCTION only information here

services:
  spa:
    ports:
      - 80
    networks:
      - reshapebackend_default

networks:
  reshapebackend_default:
    external: true
  